#!/usr/bin/env python3
"""
Build the Organoid Protocol Atlas knowledge graph (SQLite, Datasette-servable).

Mirrors the CaseStack/epstein-datasette pattern: a self-contained SQLite DB with
FTS5 + sync triggers, faceted tables, and canned comparison queries (configured in
serve/metadata.yaml). Reads the Tier-1 predictions (local OrganoidProtocol records)
+ the corpus manifest into:
  - protocols : one row per paper (the recipe card header)
  - reagents  : one row per reagent (signaling factor / supplement) with evidence
  - reagents_fts : FTS5 over name/role/evidence_quote

The DB carries SHORT evidence quotes (single-sentence citation snippets) + DOIs +
per-row license, in the CaseStack "citation-backed snippet" style. The .db is
git-ignored (regenerated by this script); only this builder + the Datasette config
are committed.

Run:  python pipeline/build_kg.py   ->  data/kg/atlas.db
"""

from __future__ import annotations

import csv
import json
import sqlite3
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PRED = REPO / "data" / "predictions" / "local"
BUNDLES = REPO / "data" / "evidence_bundles" / "local"
CORPUS = REPO / "data" / "corpus" / "pmc_oa_25.tsv"
DB = REPO / "data" / "kg" / "atlas.db"

SCHEMA = """
DROP TABLE IF EXISTS protocols;
DROP TABLE IF EXISTS reagents;
DROP TABLE IF EXISTS reagents_fts;

CREATE TABLE protocols (
    pmcid TEXT PRIMARY KEY,
    doi TEXT,
    organoid_type TEXT,
    species TEXT,
    source_cell_type TEXT,
    matrix TEXT,
    base_media TEXT,
    base_media_reporting TEXT,
    first_author TEXT,
    year TEXT,
    journal TEXT,
    license TEXT,
    gold_candidate TEXT,
    n_signaling_factors INTEGER,
    n_supplements INTEGER,
    reagents_grounded INTEGER,
    reagents_total INTEGER,
    grounding_rate REAL,
    extractor TEXT
);

CREATE TABLE reagents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pmcid TEXT REFERENCES protocols(pmcid),
    doi TEXT,
    organoid_type TEXT,
    kind TEXT,            -- signaling | supplement | small_molecule
    name TEXT,
    role TEXT,
    value REAL,
    unit TEXT,
    canonical_unit TEXT,
    evidence_quote TEXT,
    grounded INTEGER,
    suspect_unit INTEGER  -- deterministic sanity flag (e.g. growth factor in mg/mL)
);

-- Source methods text, for the in-context evidence highlighter (local serving).
DROP TABLE IF EXISTS sources;
CREATE TABLE sources (
    pmcid TEXT PRIMARY KEY,
    license TEXT,
    methods_text TEXT,
    supplementary_text TEXT
);

CREATE VIRTUAL TABLE reagents_fts USING fts5(
    name, role, evidence_quote, content='reagents', content_rowid='id'
);
CREATE TRIGGER reagents_ai AFTER INSERT ON reagents BEGIN
    INSERT INTO reagents_fts(rowid, name, role, evidence_quote)
    VALUES (new.id, new.name, new.role, new.evidence_quote);
END;

CREATE INDEX idx_reagents_pmcid ON reagents(pmcid);
CREATE INDEX idx_reagents_name ON reagents(name);
CREATE INDEX idx_reagents_kind ON reagents(kind);
CREATE INDEX idx_protocols_type ON protocols(organoid_type);
"""


def load_corpus_meta() -> dict:
    meta = {}
    for r in csv.DictReader(open(CORPUS), delimiter="\t"):
        meta[r["pmcid"]] = r
    return meta


def main():
    DB.parent.mkdir(parents=True, exist_ok=True)
    if DB.exists():
        DB.unlink()
    conn = sqlite3.connect(DB)
    conn.executescript(SCHEMA)
    meta = load_corpus_meta()

    n_protocols = n_reagents = 0
    for pf in sorted(PRED.glob("*.json")):
        pmcid = pf.stem
        p = json.loads(pf.read_text())
        cm = meta.get(pmcid, {})
        # organoid_type is curated ground-truth in the corpus manifest -> use it;
        # don't trust the LLM's guess (it misclassified 5/25).
        oty = cm.get("organoid_type") or p.get("organoid_type")

        def add_reagents(items, kind):
            nonlocal n_reagents
            for r in items or []:
                conc = r.get("concentration") or {}
                ev = r.get("evidence") or {}
                u = (conc.get("canonical_unit") or conc.get("unit") or "").lower()
                suspect = 1 if (kind == "signaling" and u == "mg/ml") else 0
                conn.execute(
                    "INSERT INTO reagents(pmcid,doi,organoid_type,kind,name,role,value,unit,"
                    "canonical_unit,evidence_quote,grounded,suspect_unit) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",
                    (pmcid, p.get("source_doi"), oty, kind,
                     r.get("name"), r.get("role"), conc.get("value"), conc.get("unit"),
                     conc.get("canonical_unit"), ev.get("quote"), 1 if ev.get("quote") else 0, suspect),
                )
                n_reagents += 1

        sf = p.get("signaling_factors") or []
        sup = p.get("media_supplements") or []
        grounded = sum(1 for r in sf if (r.get("evidence") or {}).get("quote"))
        bm = p.get("base_media") or {}
        sc = p.get("source_cells") or {}
        conn.execute(
            "INSERT INTO protocols VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (pmcid, p.get("source_doi"), oty, sc.get("species"),
             sc.get("cell_type"), (p.get("matrix") or {}).get("name"), bm.get("name"),
             bm.get("reporting"), cm.get("first_author"), cm.get("year"),
             cm.get("journal"), cm.get("license"), cm.get("gold_candidate"),
             len(sf), len(sup), grounded, len(sf),
             round(grounded / len(sf), 3) if sf else None, p.get("extractor_version")),
        )
        add_reagents(sf, "signaling")
        add_reagents(sup, "supplement")
        add_reagents(p.get("small_molecules"), "small_molecule")

        # source methods text for the in-context highlighter
        bpath = BUNDLES / f"{pmcid}.json"
        if bpath.exists():
            b = json.loads(bpath.read_text())
            conn.execute("INSERT INTO sources VALUES (?,?,?,?)",
                         (pmcid, cm.get("license"), b.get("methods_text", ""),
                          b.get("supplementary_text", "")))
        n_protocols += 1

    conn.execute("INSERT INTO reagents_fts(reagents_fts) VALUES ('optimize')")
    conn.commit()
    conn.close()
    print(f"Built {DB}: {n_protocols} protocols, {n_reagents} reagents")


if __name__ == "__main__":
    main()
