#!/usr/bin/env python3
"""
Build the Organoid Protocol Atlas knowledge graph (SQLite, Datasette-servable).

Mirrors the CaseStack/epstein-datasette pattern: a self-contained SQLite DB with
FTS5 + sync triggers, faceted tables, and canned comparison queries (configured in
serve/metadata.yaml). Reads the Tier-1 predictions (local OrganoidProtocol records)
+ the corpus manifest into:
  - protocols : one row per paper (the recipe card header)
  - reagents  : one row per reagent (signaling factor / supplement) with evidence
  - reagents_fts : FTS5 over name/role/evidence_quote

The DB carries SHORT evidence quotes (single-sentence citation snippets) + DOIs +
per-row license, in the CaseStack "citation-backed snippet" style. The .db is
git-ignored (regenerated by this script); only this builder + the Datasette config
are committed.

Run:  python pipeline/build_kg.py   ->  data/kg/atlas.db
"""

from __future__ import annotations

import csv
import json
import re
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from normalize import build_canon_map, canon_unit  # noqa: E402

# qPCR/TaqMan assay IDs (e.g. "Hs00950669_m1") misclassified as culture reagents (#234) —
# these are genes the paper MEASURED, not factors added to the culture; drop them.
_TAQMAN_RE = re.compile(r"\b[A-Z]{2}\d{6,8}_[a-z0-9]+\b", re.I)


def clean_year(y) -> str | None:
    """Reject implausible extracted years (#225): protocols.io created_on epoch sliced to
    '1715' etc. Keep only plausible publication years."""
    try:
        yi = int(str(y).strip()[:4])
    except (ValueError, TypeError):
        return None
    return str(yi) if 1990 <= yi <= 2027 else None


def select_reagents(items, canon_map):
    """#234 drop qPCR/TaqMan assay IDs (measured genes, not added factors);
    #235 dedup by canonical name within a protocol, keeping the dose-bearing mention.
    Returns the chosen reagent dicts in first-appearance order."""
    best: dict = {}
    order: list = []
    for r in items or []:
        nm = r.get("name")
        ev = r.get("evidence") or {}
        if _TAQMAN_RE.search(ev.get("quote") or "") or _TAQMAN_RE.search(nm or ""):
            continue
        canon = canon_map.get(nm, nm)
        key = (canon or "").strip().lower()
        if not key:
            continue
        has_val = (r.get("concentration") or {}).get("value") is not None
        if key in best:
            if has_val and not best[key][1]:
                best[key] = (r, has_val)
            continue
        best[key] = (r, has_val)
        order.append(key)
    return [best[k][0] for k in order]

REPO = Path(__file__).resolve().parent.parent
PRED = REPO / "data" / "predictions" / "local"
PRED2 = REPO / "data" / "predictions" / "local" / "tier2"
BUNDLES = REPO / "data" / "evidence_bundles" / "local"
CORPUS = REPO / "data" / "corpus" / "corpus.tsv"
DB = REPO / "data" / "kg" / "atlas.db"

SCHEMA = """
DROP TABLE IF EXISTS protocols;
DROP TABLE IF EXISTS reagents;
DROP TABLE IF EXISTS reagents_fts;

CREATE TABLE protocols (
    pmcid TEXT PRIMARY KEY,
    doi TEXT,
    organoid_type TEXT,
    species TEXT,
    source_cell_type TEXT,
    matrix TEXT,
    base_media TEXT,
    base_media_reporting TEXT,
    first_author TEXT,
    year TEXT,
    journal TEXT,
    license TEXT,
    gold_candidate TEXT,
    n_signaling_factors INTEGER,
    n_supplements INTEGER,
    n_figure_confirmed INTEGER,
    reagents_grounded INTEGER,
    reagents_total INTEGER,
    grounding_rate REAL,
    extractor TEXT,
    passaging TEXT,
    timeline TEXT,
    assay_endpoints TEXT,
    publication_type TEXT,
    stages TEXT,
    is_generation_protocol INTEGER
);

CREATE TABLE reagents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pmcid TEXT REFERENCES protocols(pmcid),
    doi TEXT,
    organoid_type TEXT,
    kind TEXT,            -- signaling | supplement | small_molecule
    name TEXT,
    canonical TEXT,       -- normalized entity (collapses synonyms: bFGF->FGF2, RSPO1->R-spondin1)
    role TEXT,
    value REAL,
    unit TEXT,
    canonical_unit TEXT,
    evidence_quote TEXT,
    grounded INTEGER,
    suspect_unit INTEGER, -- deterministic sanity flag (e.g. growth factor in mg/mL)
    figure_confirmed INTEGER  -- Tier-2: this canonical factor also appears in a figure schematic
);

-- Source methods text, for the in-context evidence highlighter (local serving).
DROP TABLE IF EXISTS sources;
CREATE TABLE sources (
    pmcid TEXT PRIMARY KEY,
    license TEXT,
    methods_text TEXT,
    supplementary_text TEXT
);

CREATE VIRTUAL TABLE reagents_fts USING fts5(
    name, role, evidence_quote, content='reagents', content_rowid='id'
);
CREATE TRIGGER reagents_ai AFTER INSERT ON reagents BEGIN
    INSERT INTO reagents_fts(rowid, name, role, evidence_quote)
    VALUES (new.id, new.name, new.role, new.evidence_quote);
END;

CREATE INDEX idx_reagents_pmcid ON reagents(pmcid);
CREATE INDEX idx_reagents_name ON reagents(name);
CREATE INDEX idx_reagents_kind ON reagents(kind);
CREATE INDEX idx_protocols_type ON protocols(organoid_type);
"""


def load_corpus_meta() -> dict:
    meta = {}
    for r in csv.DictReader(open(CORPUS), delimiter="\t"):
        meta[r["pmcid"]] = r
    return meta


def main():
    DB.parent.mkdir(parents=True, exist_ok=True)
    if DB.exists():
        DB.unlink()
    conn = sqlite3.connect(DB)
    conn.executescript(SCHEMA)
    meta = load_corpus_meta()

    # corpus-wide reagent-name normalization map (entity canonicalization)
    all_names = []
    for pf in PRED.glob("*.json"):
        pp = json.loads(pf.read_text())
        for kk in ("signaling_factors", "media_supplements", "small_molecules"):
            all_names += [r.get("name") for r in (pp.get(kk) or []) if isinstance(r, dict)]
    canon_map = build_canon_map(all_names)

    # Tier-2 cross-modal corroboration: canonical factors a vision pass confirmed
    # in a figure schematic, per paper. Used to annotate (not add) reagents.
    fig_confirmed: dict[str, set] = {}
    if PRED2.exists():
        for f2 in PRED2.glob("*.json"):
            t2 = json.loads(f2.read_text())
            confirmed = {c.get("canonical") for fig in t2.get("figures", [])
                         for c in fig.get("culture_factors", []) if c.get("canonical")}
            if confirmed:
                fig_confirmed[t2["pmcid"]] = confirmed

    n_protocols = n_reagents = 0
    for pf in sorted(PRED.glob("*.json")):
        pmcid = pf.stem
        p = json.loads(pf.read_text())
        cm = meta.get(pmcid, {})
        # organoid_type is curated ground-truth in the corpus manifest -> use it;
        # don't trust the LLM's guess (it misclassified 5/25).
        oty = cm.get("organoid_type") or p.get("organoid_type")

        def add_reagents(items, kind):
            nonlocal n_reagents
            for r in select_reagents(items, canon_map):
                conc = r.get("concentration") or {}
                ev = r.get("evidence") or {}
                cunit = canon_unit(conc.get("canonical_unit") or conc.get("unit"))
                u = (cunit or "").lower()
                suspect = 1 if (kind == "signaling" and u == "mg/ml") else 0
                nm = r.get("name")
                canon = canon_map.get(nm, nm)
                fconf = 1 if canon in fig_confirmed.get(pmcid, set()) else 0
                conn.execute(
                    "INSERT INTO reagents(pmcid,doi,organoid_type,kind,name,canonical,role,value,unit,"
                    "canonical_unit,evidence_quote,grounded,suspect_unit,figure_confirmed) "
                    "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                    (pmcid, p.get("source_doi"), oty, kind,
                     nm, canon, r.get("role"), conc.get("value"), conc.get("unit"),
                     cunit, ev.get("quote"), 1 if ev.get("quote") else 0,
                     suspect, fconf),
                )
                n_reagents += 1

        sf = p.get("signaling_factors") or []
        sup = p.get("media_supplements") or []
        grounded = sum(1 for r in sf if (r.get("evidence") or {}).get("quote"))
        conf_set = fig_confirmed.get(pmcid, set())
        n_conf = sum(1 for r in sf if canon_map.get(r.get("name"), r.get("name")) in conf_set)
        bm = p.get("base_media") or {}
        sc = p.get("source_cells") or {}
        pgd = p.get("passaging") or {}
        passaging_s = " · ".join(str(x) for x in [
            pgd.get("method"), pgd.get("split_ratio"),
            (f"{pgd.get('interval_days')}d" if pgd.get("interval_days") else None)] if x)
        timeline_s = " → ".join(
            f"{t.get('name')} (d{t.get('day_start') if t.get('day_start') is not None else '?'}"
            f"–{t.get('day_end') if t.get('day_end') is not None else '?'})"
            for t in (p.get("timeline") or []) if t.get("name"))
        endpoints_s = " · ".join(str(x) for x in (p.get("assay_endpoints") or []))
        # v0.6 stages[] (schema #226) carried through to the export the recipe renderer
        # (#228) reads. Stored as JSON text; export_public re-parses to an array. Empty
        # when the prediction has no stages (pre-stages-run) -> renderer falls back to timeline.
        raw_stages = p.get("stages") or []
        stages_json = json.dumps(raw_stages, ensure_ascii=False) if raw_stages else None
        is_gen = p.get("is_generation_protocol")
        is_gen_i = None if is_gen is None else int(bool(is_gen))
        conn.execute(
            "INSERT INTO protocols VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (pmcid, p.get("source_doi"), oty, sc.get("species"),
             sc.get("cell_type"), (p.get("matrix") or {}).get("name"), bm.get("name"),
             bm.get("reporting"), cm.get("first_author"), clean_year(cm.get("year")),
             cm.get("journal"), cm.get("license"), cm.get("gold_candidate"),
             len(sf), len(sup), n_conf, grounded, len(sf),
             round(grounded / len(sf), 3) if sf else None, p.get("extractor_version"),
             passaging_s or None, timeline_s or None, endpoints_s or None,
             p.get("publication_type"), stages_json, is_gen_i),
        )
        add_reagents(sf, "signaling")
        add_reagents(sup, "supplement")
        add_reagents(p.get("small_molecules"), "small_molecule")

        # source methods text for the in-context highlighter
        bpath = BUNDLES / f"{pmcid}.json"
        if bpath.exists():
            b = json.loads(bpath.read_text())
            conn.execute("INSERT INTO sources VALUES (?,?,?,?)",
                         (pmcid, cm.get("license"), b.get("methods_text", ""),
                          b.get("supplementary_text", "")))
        n_protocols += 1

    conn.execute("INSERT INTO reagents_fts(reagents_fts) VALUES ('optimize')")
    conn.commit()
    conn.close()
    print(f"Built {DB}: {n_protocols} protocols, {n_reagents} reagents")


if __name__ == "__main__":
    main()
